//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport_club
    {
        public int id_club { get; set; }
        public Nullable<int> id_kind { get; set; }
        public string Name_club { get; set; }
        public string Text_club { get; set; }
        public Nullable<System.DateTime> CreateDate_club { get; set; }
        public byte[] Image_club { get; set; }
    
        public virtual Kind_sport Kind_sport { get; set; }
    }
}
